// Schedule data for all days with proper time ranges and positions
interface ScheduleEvent {
  id: number
  title: string
  speaker: string
  type: "X Space" | "Workshop" | "Tour" | "Community"
  stage: "MainStage"
  startTime: string // e.g., "11:00"
  endTime: string // e.g., "12:00"
  timeSlotStart: number // index position for start time
  timeSlotEnd: number // index position for end time
  duration: number // number of time slots this event spans
}

interface StageSchedule {
  [stageName: string]: ScheduleEvent[]
}

interface DaySchedule {
  [key: string]: StageSchedule
}

// Time slots mapping (14 total slots as per Figma design)
const timeSlots = [
  "11:00 am", // 0
  "Midday", // 1 (12:00)
  "1:00 pm", // 2
  "2:00 pm", // 3
  "3:00 pm", // 4
  "4:00 pm", // 5
  "5:00 pm", // 6
  "6:00 pm", // 7
  "8:00 pm", // 8
  "9:00 pm", // 9
  "10:00 pm", // 10
  "11:00 pm", // 11
  "Midnight", // 12
  "1:00 am", // 13
]

const stages = ["MainStage"]

const scheduleData: DaySchedule = {
  "sept-24": {
    MainStage: [
      {
        id: 1,
        title: "The 101 on Decentraland Art Week: Launch Your Own Gallery!",
        speaker: "Bay",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
      },
      {
        id: 2,
        title:
          "Behind the Build: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
      },
      {
        id: 3,
        title: "LIVE TOUR 1",
        speaker: "Bay",
        type: "Tour",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
      },
      {
        id: 4,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw / Bay?",
        type: "Workshop",
        stage: "MainStage",
        startTime: "2:00",
        endTime: "2:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
      },
      {
        id: 5,
        title:
          "Find Your Next Collab! Easy, Fun Networking Led by a Virtual Host",
        speaker: "Bay - DANA",
        type: "Workshop",
        stage: "MainStage",
        startTime: "3:00",
        endTime: "3:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
      },
      {
        id: 6,
        title: "Your Art in Decentraland? Here’s How to Make It Happen",
        speaker: "Kim",
        type: "X Space",
        stage: "MainStage",
        startTime: "8:00",
        endTime: "8:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
      },
      {
        id: 7,
        title: "LIVE TOUR 2",
        speaker: "Bay / Kim",
        type: "Tour",
        stage: "MainStage",
        startTime: "9:00",
        endTime: "9:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
      },
      {
        id: 8,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw / Bay",
        type: "Workshop",
        stage: "MainStage",
        startTime: "10:00",
        endTime: "10:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
      },
      {
        id: 9,
        title:
          "Behind the Build: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana",
        type: "Workshop",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
      },
      {
        id: 10,
        title: "RAGE! Art & Industrial Music",
        speaker: "RAGE",
        type: "Community",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
      },
    ],
  },
  "sept-25": {
    MainStage: [
      {
        id: 11,
        title: "The Insider’s Guide to Creating for Virtual Art Shows",
        speaker: "Bay",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
      },
      {
        id: 12,
        title: "Using Brave as a Creator: Get Rewarded while Getting Noticed",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
      },
      {
        id: 13,
        title: "LIVE TOUR 3",
        speaker: "Bay",
        type: "Tour",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
      },
      {
        id: 14,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw / Bay / Kim",
        type: "Workshop",
        stage: "MainStage",
        startTime: "2:00",
        endTime: "2:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
      },
      {
        id: 15,
        title: "Digital to Physical: Take Your 3D Art Anywhere with AR",
        speaker: "Artivive",
        type: "Workshop",
        stage: "MainStage",
        startTime: "3:00",
        endTime: "3:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
      },
      {
        id: 16,
        title:
          "Curator Secrets: How to Be Selected for Art Shows — Virtual and IRL",
        speaker: "Bay",
        type: "Workshop",
        stage: "MainStage",
        startTime: "4:00",
        endTime: "4:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
      },
      {
        id: 17,
        title: "Brave at Decentraland Art Week: Pro Tips for Creators",
        speaker: "Brave x Decentraland",
        type: "X Space",
        stage: "MainStage",
        startTime: "8:00",
        endTime: "8:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
      },
      {
        id: 18,
        title: "Using Brave as a Creator: Get Rewarded while Getting Noticed",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "9:00",
        endTime: "9:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
      },
      {
        id: 19,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw / Bay / Kim",
        type: "Workshop",
        stage: "MainStage",
        startTime: "10:00",
        endTime: "10:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
      },
      {
        id: 20,
        title: "Digital to Physical: Take Your 3D Art Anywhere with AR",
        speaker: "Artivive",
        type: "Workshop",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
      },
      {
        id: 21,
        title: "Grass to the Moon - DJ Abillitea live in Facemoon Gallery",
        speaker: "Facemoon",
        type: "Community",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
      },
    ],
  },
  "sept-26": {
    MainStage: [
      {
        id: 22,
        title: "AI for 3D Art: A Beginner’s Guide",
        speaker: "Bay",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 0,
        timeSlotEnd: 0,
        duration: 1,
      },
      {
        id: 23,
        title:
          "Master AI Design with ImagineArt’s Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
      },
      {
        id: 24,
        title: "LIVE TOUR 6",
        speaker: "Bay",
        type: "Tour",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
      },
      {
        id: 25,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "2:00",
        endTime: "2:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
      },
      {
        id: 26,
        title: "Instant Assets: Creating Decentraland-Ready 3D Models",
        speaker: "CSM",
        type: "Workshop",
        stage: "MainStage",
        startTime: "3:00",
        endTime: "3:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
      },
      {
        id: 27,
        title: "AI-Powered Creation in Decentraland",
        speaker: "Kim",
        type: "X Space",
        stage: "MainStage",
        startTime: "8:00",
        endTime: "8:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
      },
      {
        id: 28,
        title: "LIVE TOUR 7",
        speaker: "Kim /Dana",
        type: "Tour",
        stage: "MainStage",
        startTime: "9:00",
        endTime: "9:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
      },
      {
        id: 29,
        title:
          "Master AI Design with ImagineArt’s Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "10:00",
        endTime: "10:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
      },
      {
        id: 30,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
      },
      {
        id: 31,
        title: "Meta Beast Roaming Party @ Roustan Gallery",
        speaker: "Roustan/DJ Make",
        type: "Community",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
      },
    ],
  },
  "sept-27": {
    MainStage: [
      {
        id: 32,
        title:
          "Behind the Building: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
      },
      {
        id: 33,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw / Bay?",
        type: "Workshop",
        stage: "MainStage",
        startTime: "1:00",
        endTime: "1:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
      },
      {
        id: 34,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw / Bay?",
        type: "Workshop",
        stage: "MainStage",
        startTime: "2:00",
        endTime: "2:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
      },
      {
        id: 35,
        title:
          "Curator Secrets: How to Be Selected for Art Shows — Virtual and IRL",
        speaker: "Bay",
        type: "Workshop",
        stage: "MainStage",
        startTime: "3:00",
        endTime: "3:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
      },
      {
        id: 36,
        title: "Using Brave as a Creator: Get Rewarded while Getting Noticed",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "4:00",
        endTime: "4:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
      },
      {
        id: 37,
        title:
          "Master AI Design with ImagineArt’s Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "5:00",
        endTime: "5:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
      },
      {
        id: 38,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "6:00",
        endTime: "6:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
      },
      {
        id: 39,
        title: "Instant Assets: Creating Decentraland-Ready 3D Models",
        speaker: "CSM",
        type: "Workshop",
        stage: "MainStage",
        startTime: "8:00",
        endTime: "8:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
      },
      {
        id: 40,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw / Bay?",
        type: "Workshop",
        stage: "MainStage",
        startTime: "9:00",
        endTime: "9:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
      },
      {
        id: 41,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw / Bay?",
        type: "Workshop",
        stage: "MainStage",
        startTime: "10:00",
        endTime: "10:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
      },
      {
        id: 42,
        title: "Audio Hot Lab Party w/ Silvio De Candia",
        speaker: "AudioHotLab",
        type: "Community",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "11:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
      },
    ],
  },
}

const dateOptions = [
  { key: "sept-23", date: "SEPT 23", label: "Pre event" },
  { key: "sept-24", date: "SEPT 24", label: "Day One" },
  { key: "sept-25", date: "SEPT 25", label: "Day Two" },
  { key: "sept-26", date: "SEPT 26", label: "Day Three" },
  { key: "sept-27", date: "SEPT 27", label: "Day Four" },
]

export type { ScheduleEvent, StageSchedule, DaySchedule }
export { timeSlots, stages, scheduleData, dateOptions }
