name: release

on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # - name: node.js 12
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 12
      #     cache: 'npm'

      # - name: installing
      #   run: npm ci

      - name: building
        # run: npm run build
        run: mkdir -p public && echo "<h1>Hello Metaverse Festival</h1>" >> public/index.html

      # publish to gh pages
      - name: publishing documents
        uses: peaceiris/actions-gh-pages@v3
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          CNAME: https://themetaversefestival.io/