name: release

on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # - name: node.js 12
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 12
      #     registry-url: https://registry.npmjs.org/
      #     cache: 'npm'

      # - name: installing
      #   run: npm ci

      - name: building
        # run: npm run build
        run: mkdir -p public && echo "<h1>Hello Metaverse Festival</h1>"

      # publish to gh pages
      - name: publishing documents
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public